# Generated by Django 3.2.2 on 2021-05-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaEnigma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enigma', models.IntegerField(unique=True, verbose_name='Número do enigma')),
                ('resposta', models.CharField(max_length=200, verbose_name='Resposta do enigma')),
            ],
        ),
        migrations.CreateModel(
            name='VencedorEnigmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
