# Generated by Django 3.2.3 on 2021-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enigma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enigma', models.PositiveIntegerField(unique=True, verbose_name='Número do enigma')),
                ('pergunta', models.CharField(max_length=100, verbose_name='Pergunta')),
                ('pagina', models.CharField(max_length=100, verbose_name='Nome da página')),
                ('resposta', models.CharField(max_length=100, verbose_name='Resposta do enigma')),
            ],
        ),
    ]
