# Generated by Django 3.2.3 on 2021-05-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enigmas', '0002_enigma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RespostaEnigma',
        ),
    ]
