# Generated by Django 3.2.2 on 2021-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210527_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('P', 'Palestras'), ('H', 'Hackathon'), ('M', 'Minicursos'), ('R', 'Mesas Redondas'), ('A', 'Maratona de programação')], max_length=1, verbose_name='Tipo de Postagem'),
        ),
    ]
