# Generated by Django 3.2.2 on 2021-05-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('P', 'Palestras'), ('H', 'Hackathon'), ('M', 'Minicursos'), ('R', 'Mesas Redondas'), ('A', 'Maratona'), ('O', 'Oficinas'), ('B', 'BATE-PAPO')], max_length=1, verbose_name='Tipo de Postagem'),
        ),
    ]
