# Generated by Django 3.2.2 on 2021-05-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Nome da configuração')),
                ('active', models.BooleanField(default=False, verbose_name='Status da configuração')),
            ],
        ),
    ]
